### ISSUE TITLE
验证提示问题

### ISSUE THREAD

**Issue by zhw2590582** [ciaoca/cxValidation#1]
提交验证失败的时候仅仅是获取焦点么，可以考虑添加个类名，好控制样式。
我设置了验证错误时候的提示，发现是添加到body前的，而不是添加到表单的当前项，这样子也不好控制样式。

**Comment by ciaoca** [comment]
感谢提出建议，目前提示内容这块在考虑怎么处理。
在移动端下，输入框获取焦点时会弹出输入法，然后输入框会被顶起，这样对用户输入很方便，不过提示内容可能会被看不到。

移动端界面比较小，在输入框附近做提示内容的设计还是比较少，目前在顶部进行提示，不过由于被顶起，还是很容易因为偏移导致看不到。

目前还可以自定义错误提示的处理，例如结合 cxDialog 或其他的对话框，先显示提示内容，用户点击确定后，再让输入框获取焦点。
