### ISSUE TITLE
可以进行正则表达式的验证吗？

### ISSUE THREAD

**Issue by NiroDu** [ciaoca/cxValidation#2]
插件可以做正则表达式吗？
正则的自定义写法该怎么写？
在文档没看到呢。

**Comment by ciaoca** [comment]
暂不支持在规则上写正则
可以自定义的验证方法，在方法中写明正则，然后使用 call 调用外部方法进行验证
DEMO: http://code.ciaoca.com/javascript/cxValidation/demo/call

**Comment by NiroDu** [comment]
谢谢你啦~
